import Nav from "@/components/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} no-scroll`}>
        <NextAuthProvider>
          <section className="flex flex-col flex-center">
            <Nav />
            {children}
            <Footer />
          </section>
        </NextAuthProvider>
      </body>
    </html>
  );
}
